@startuml
left to right direction

actor "Usuário" as Usuario

rectangle "Sistema ContentFlow" {

  package "📅 Planejamento" {

    (Criar planejamento) as CP
    (Visualizar calendário) as VC
    (Visualizar posts por data) as VPD

  }

  package "📝 Posts" {

    (Adicionar post) as AP
    (Editar post) as EP
    (Excluir post) as EX
    (Alterar status do post) as SP
    (Buscar post por título) as BP
    (Filtrar posts por status) as FP

  }

  package "📊 Dashboard" {

    (Visualizar dashboard) as VD
    (Visualizar desempenho mensal) as VM
    (Visualizar métricas de alcance) as MA

  }

}

Usuario --> CP
Usuario --> VC
Usuario --> VPD

Usuario --> AP
Usuario --> EP
Usuario --> EX
Usuario --> SP
Usuario --> BP
Usuario --> FP

Usuario --> VD
Usuario --> VM
Usuario --> MA


EP ..> AP : <<include>>
EX ..> AP : <<include>>
SP ..> EP : <<extend>>

VM ..> VD : <<include>>
MA ..> VD : <<include>>

@enduml